import request from 'supertest'
import { describe, expect, it } from 'vitest'
import { auth, registerAndLogin } from './helpers.js'

const day = (offset: number) =>
  new Date(Date.now() - offset * 24 * 3600 * 1000).toISOString().slice(0, 10)

describe('tracking', () => {
  it('upsert theo ngày (một bản ghi/ngày), null xóa chỉ số, list cũ → mới, xóa', async () => {
    const { app, token } = await registerAndLogin()
    await request(app)
      .put(`/api/tracking/logs/${day(1)}`)
      .set(auth(token))
      .send({ weightKg: 66, systolic: 130, diastolic: 85, sleepHours: 6.5, mood: 3 })
      .expect(200)
    const again = await request(app)
      .put(`/api/tracking/logs/${day(1)}`)
      .set(auth(token))
      .send({ weightKg: 65.5, sleepHours: null })
      .expect(200)
    expect(again.body.data).toMatchObject({ weightKg: 65.5, systolic: 130, sleepHours: null })

    await request(app)
      .put(`/api/tracking/logs/${day(0)}`)
      .set(auth(token))
      .send({ weightKg: 65 })
      .expect(200)
    const list = await request(app).get('/api/tracking/logs').set(auth(token)).expect(200)
    expect(list.body.data.map((l: { date: string }) => l.date)).toEqual([day(1), day(0)])

    await request(app)
      .delete(`/api/tracking/logs/${day(0)}`)
      .set(auth(token))
      .expect(200)
    await request(app)
      .delete(`/api/tracking/logs/${day(0)}`)
      .set(auth(token))
      .expect(404)
  })

  it('validate: tương lai, tâm thu ≤ tâm trương, ngoài khoảng', async () => {
    const { app, token } = await registerAndLogin()
    await request(app)
      .put(`/api/tracking/logs/${day(-5)}`)
      .set(auth(token))
      .send({ weightKg: 60 })
      .expect(400)
    await request(app)
      .put(`/api/tracking/logs/${day(0)}`)
      .set(auth(token))
      .send({ systolic: 80, diastolic: 90 })
      .expect(400)
    await request(app)
      .put(`/api/tracking/logs/${day(0)}`)
      .set(auth(token))
      .send({ mood: 9 })
      .expect(400)
    await request(app).put('/api/tracking/logs/2026-13-01').set(auth(token)).send({}).expect(400)
  })

  it('analyze cần nhật ký, lưu HealthAdvice, đánh dấu đề xuất đã làm, user khác không thấy', async () => {
    const a = await registerAndLogin('A')
    const b = await registerAndLogin('B')
    await request(a.app).post('/api/tracking/analyze').set(auth(a.token)).send({}).expect(400)

    await request(a.app)
      .put(`/api/tracking/logs/${day(2)}`)
      .set(auth(a.token))
      .send({ weightKg: 66 })
      .expect(200)
    await request(a.app)
      .put(`/api/tracking/logs/${day(0)}`)
      .set(auth(a.token))
      .send({ systolic: 145, diastolic: 92 })
      .expect(200)

    const an = await request(a.app)
      .post('/api/tracking/analyze')
      .set(auth(a.token))
      .send({ days: 30 })
      .expect(201)
    expect(an.body.data.logCount).toBe(2)
    expect(an.body.data.alerts[0].level).toBe('warning')
    expect(an.body.data.suggestions[0].done).toBe(false)
    expect(an.body.data.disclaimer).toBeTypeOf('string')

    const done = await request(a.app)
      .patch(`/api/tracking/advice/${an.body.data.id}/suggestions/0`)
      .set(auth(a.token))
      .send({ done: true })
      .expect(200)
    expect(done.body.data.suggestions[0].done).toBe(true)

    await request(b.app)
      .patch(`/api/tracking/advice/${an.body.data.id}/suggestions/0`)
      .set(auth(b.token))
      .send({ done: true })
      .expect(404)
    const list = await request(b.app).get('/api/tracking/advice').set(auth(b.token)).expect(200)
    expect(list.body.data).toHaveLength(0)
  })
})
